Implementing new trait for osu! API to return response body on errors
boraarslan/mapper-influence pull request #78
Opened 2023-03-29 19:19 UTC by 112batuhan

Implemented a new trait for request response struct.

Also implemented a new error struct. This error struct contains a struct variant with the status code and the body in String form if the error is caused by API request. This status code can be matched with the constants defined in the [documentation](https://docs.rs/reqwest/latest/reqwest/struct.StatusCode.html).
```
assert_eq!(
    err.status(),
    Some(reqwest::StatusCode::BAD_REQUEST)
);
```

2023-03-29 19:26 UTC, Fursum submitted a review, later dismissed

2023-04-19 15:25 UTC, 112batuhan commented
The error handling is not ready yet. I will work on the error conversion in `AppError`

2023-04-25 21:53 UTC, 112batuhan commented
Completed @boraarslan

2023-04-29 16:17 UTC, boraarslan commented on mi-osu-api/src/lib.rs
> +    #[error("Request failed because of internal errors before or after the request.")]
```suggestion
    #[error("An internal error has occurred.")]
```

2023-04-29 16:19 UTC, boraarslan requested changes

2023-04-29 16:19 UTC, boraarslan commented on mi-osu-api/src/auth.rs
> +    response_result
```suggestion
    response_result.try_deserialising().await
```
Can you change this for all alike calls?

2023-04-29 18:00 UTC, boraarslan approved these changes
Great job

2023-04-29 18:01 UTC, merged